#!/bin/bash
# TanukiParser Linux Build Script for WSL
# Generated by Antigravity 🐾

# プロジェクトのディレクトリに移動（このスクリプトがある場所）
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

echo "🐾 TanukiParser Linux Build (musl) starting..."

# Rustのmuslターゲットでビルド
# --release フラグで最適化
# --target x86_64-unknown-linux-musl で静的リンク
~/.cargo/bin/cargo build --target x86_64-unknown-linux-musl --release

if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
    echo "Binary location: target/x86_64-unknown-linux-musl/release/TanukiParser"
    
    # 実行権限の確認
    chmod +x target/x86_64-unknown-linux-musl/release/TanukiParser
else
    echo "❌ Build failed!"
    exit 1
fi
