# Generated by TanukiParser - Namespace: SonicEther
from enum import Enum, auto

class TokenType(Enum):
    OPEN_BRACKET = auto()
    CLOSE_BRACKET = auto()
    OPEN_PAREN = auto()
    CLOSE_PAREN = auto()
    OPEN_PAREN_FULL = auto()
    CLOSE_PAREN_FULL = auto()
    CHORD_MARK = auto()
    TEXT = auto()
    NL = auto()

class LyricsParser:
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.token = None
        self.results = []
    
    def lyrics(self):
        ret_val = None
        ret_val_0 = None
        while (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.CHORD_MARK) or (self.token.token_type == TokenType.NL):
            ret_val_0 = self.element()
        return ret_val
    
    def element(self):
        ret_val = None
        ret_val_0 = None
        match self.token.token_type:
            case TokenType.OPEN_BRACKET | TokenType.OPEN_PAREN | TokenType.OPEN_PAREN_FULL | TokenType.CHORD_MARK:
                ret_val_0 = self.tag()
            case TokenType.TEXT:
                ret_val_0 = self.text_content()
            case TokenType.OPEN_BRACKET | TokenType.CLOSE_BRACKET | TokenType.OPEN_PAREN | TokenType.CLOSE_PAREN | TokenType.OPEN_PAREN_FULL | TokenType.CLOSE_PAREN_FULL | TokenType.CHORD_MARK:
                ret_val_0 = self.other_char()
            case TokenType.NL:
                ret_val_0 = self.newline()
            case _:
                pass
        return ret_val
    
    def tag(self):
        ret_val = None
        ret_val_0 = None
        match self.token.token_type:
            case TokenType.OPEN_BRACKET:
                ret_val_0 = self.bracket_tag()
            case TokenType.OPEN_PAREN:
                ret_val_0 = self.paren_tag()
            case TokenType.OPEN_PAREN_FULL:
                ret_val_0 = self.full_paren_tag()
            case TokenType.CHORD_MARK:
                ret_val_0 = self.chord_line()
            case _:
                pass
        return ret_val
    
    def bracket_tag(self):
        ret_val = None
        if (self.token.token_type != TokenType.OPEN_BRACKET):
            return None
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.CHORD_MARK):
            match self.token.token_type:
                case TokenType.TEXT:
                    if (self.token.token_type != TokenType.TEXT):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN:
                    if (self.token.token_type != TokenType.OPEN_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN:
                    if (self.token.token_type != TokenType.CLOSE_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN_FULL:
                    if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN_FULL:
                    if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CHORD_MARK:
                    if (self.token.token_type != TokenType.CHORD_MARK):
                        return None
                    self.token = self.tokenizer.get_token()
                case _:
                    pass
        if (self.token.token_type != TokenType.CLOSE_BRACKET):
            return None
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def paren_tag(self):
        ret_val = None
        if (self.token.token_type != TokenType.OPEN_PAREN):
            return None
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL) or (self.token.token_type == TokenType.CHORD_MARK):
            match self.token.token_type:
                case TokenType.TEXT:
                    if (self.token.token_type != TokenType.TEXT):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_BRACKET:
                    if (self.token.token_type != TokenType.OPEN_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_BRACKET:
                    if (self.token.token_type != TokenType.CLOSE_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN_FULL:
                    if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN_FULL:
                    if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CHORD_MARK:
                    if (self.token.token_type != TokenType.CHORD_MARK):
                        return None
                    self.token = self.tokenizer.get_token()
                case _:
                    pass
        if (self.token.token_type != TokenType.CLOSE_PAREN):
            return None
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def full_paren_tag(self):
        ret_val = None
        if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
            return None
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.CHORD_MARK):
            match self.token.token_type:
                case TokenType.TEXT:
                    if (self.token.token_type != TokenType.TEXT):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_BRACKET:
                    if (self.token.token_type != TokenType.OPEN_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_BRACKET:
                    if (self.token.token_type != TokenType.CLOSE_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN:
                    if (self.token.token_type != TokenType.OPEN_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN:
                    if (self.token.token_type != TokenType.CLOSE_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CHORD_MARK:
                    if (self.token.token_type != TokenType.CHORD_MARK):
                        return None
                    self.token = self.tokenizer.get_token()
                case _:
                    pass
        if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
            return None
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def chord_line(self):
        ret_val = None
        if (self.token.token_type != TokenType.CHORD_MARK):
            return None
        self.token = self.tokenizer.get_token()
        while (self.token.token_type == TokenType.TEXT) or (self.token.token_type == TokenType.OPEN_BRACKET) or (self.token.token_type == TokenType.CLOSE_BRACKET) or (self.token.token_type == TokenType.OPEN_PAREN) or (self.token.token_type == TokenType.CLOSE_PAREN) or (self.token.token_type == TokenType.OPEN_PAREN_FULL) or (self.token.token_type == TokenType.CLOSE_PAREN_FULL):
            match self.token.token_type:
                case TokenType.TEXT:
                    if (self.token.token_type != TokenType.TEXT):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_BRACKET:
                    if (self.token.token_type != TokenType.OPEN_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_BRACKET:
                    if (self.token.token_type != TokenType.CLOSE_BRACKET):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN:
                    if (self.token.token_type != TokenType.OPEN_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN:
                    if (self.token.token_type != TokenType.CLOSE_PAREN):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.OPEN_PAREN_FULL:
                    if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case TokenType.CLOSE_PAREN_FULL:
                    if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                        return None
                    self.token = self.tokenizer.get_token()
                case _:
                    pass
        return ret_val
    
    def text_content(self):
        ret_val = None
        if (self.token.token_type != TokenType.TEXT):
            return None
        self.results.append(self.token.content)
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def newline(self):
        ret_val = None
        if (self.token.token_type != TokenType.NL):
            return None
        self.results.append("\n")
        self.token = self.tokenizer.get_token()
        return ret_val
    
    def other_char(self):
        ret_val = None
        match self.token.token_type:
            case TokenType.OPEN_BRACKET:
                if (self.token.token_type != TokenType.OPEN_BRACKET):
                    return None
                self.results.append("[")
                self.token = self.tokenizer.get_token()
            case TokenType.CLOSE_BRACKET:
                if (self.token.token_type != TokenType.CLOSE_BRACKET):
                    return None
                self.results.append("]")
                self.token = self.tokenizer.get_token()
            case TokenType.OPEN_PAREN:
                if (self.token.token_type != TokenType.OPEN_PAREN):
                    return None
                self.results.append("(")
                self.token = self.tokenizer.get_token()
            case TokenType.CLOSE_PAREN:
                if (self.token.token_type != TokenType.CLOSE_PAREN):
                    return None
                self.results.append(")")
                self.token = self.tokenizer.get_token()
            case TokenType.OPEN_PAREN_FULL:
                if (self.token.token_type != TokenType.OPEN_PAREN_FULL):
                    return None
                self.results.append("（")
                self.token = self.tokenizer.get_token()
            case TokenType.CLOSE_PAREN_FULL:
                if (self.token.token_type != TokenType.CLOSE_PAREN_FULL):
                    return None
                self.results.append("）")
                self.token = self.tokenizer.get_token()
            case TokenType.CHORD_MARK:
                if (self.token.token_type != TokenType.CHORD_MARK):
                    return None
                self.results.append("-")
                self.token = self.tokenizer.get_token()
            case _:
                pass
        return ret_val
    
    def parse(self):
        ret_val = None
        ret_val = self.lyrics()
        return ret_val
    
