use crate::ast::{Tree, TreeKind, OpeType};
use std::io::Write;

pub struct PythonGenerator {
    ident: usize,
}

impl PythonGenerator {
    pub fn new() -> Self {
        Self { ident: 0 }
    }

    fn output(&self, s: &str, writer: &mut dyn Write) {
        let tabs = "    ".repeat(self.ident);
        writeln!(writer, "{}{}", tabs, s).unwrap();
    }

    fn format_condition(&self, conditions: &[&Tree], op: OpeType) -> String {
        let op_str = match op {
            OpeType::EqualEqual => "==",
            OpeType::NotEqual => "!=",
        };
        let join_str = match op {
            OpeType::EqualEqual => " or ",
            OpeType::NotEqual => " and ",
        };

        conditions.iter().map(|c| {
            let name = match &c.kind {
                TreeKind::ExpName(n) | TreeKind::TermName(n) => n.clone(),
                _ => "UNKNOWN".to_string(),
            };
            format!("(self.token.token_type {} TokenType.{})", op_str, name)
        }).collect::<Vec<_>>().join(join_str)
    }

    fn map_init(&self, i: &str) -> String {
        match i {
            "null" => "None".to_string(),
            "true" => "True".to_string(),
            "false" => "False".to_string(),
            _ => i.to_string(),
        }
    }
}

impl<'a> crate::generator::Generator<'a> for PythonGenerator {
    fn generate(&mut self, tree: &'a Tree<'a>, writer: &mut dyn Write) -> anyhow::Result<()> {
        match &tree.kind {
            TreeKind::Namespace { name, tokens, class_body } => {
                self.output(&format!("# Generated by TanukiParser - Namespace: {}", name), writer);
                self.output("from enum import Enum, auto", writer);
                self.output("", writer);
                self.output("class TokenType(Enum):", writer);
                self.ident += 1;
                for token in tokens {
                    self.output(&format!("{} = auto()", token), writer);
                }
                self.ident -= 1;
                self.output("", writer);
                
                self.generate(class_body, writer)?;
            }
            TreeKind::Class { name, decls, functions } => {
                self.output(&format!("class {}:", name), writer);
                self.ident += 1;
                
                // Constructor
                self.output("def __init__(self, tokenizer):", writer);
                self.ident += 1;
                self.output("self.tokenizer = tokenizer", writer);
                self.output("self.token = None", writer);
                for d in decls {
                    if let TreeKind::Decl { name, decl_type, init, .. } = &d.kind {
                        let mut val = if let Some(i) = init { self.map_init(i) } else { "None".to_string() };
                        if decl_type == "list" && val == "None" { val = "[]".to_string(); }
                        self.output(&format!("self.{} = {}", name.to_lowercase(), val), writer);
                    }
                }
                self.ident -= 1;
                self.output("", writer);

                for f in functions {
                    self.generate(f, writer)?;
                }
                
                self.ident -= 1;
            }
            TreeKind::Decl { name, init, .. } => {
                let val = if let Some(i) = init { self.map_init(i) } else { "None".to_string() };
                self.output(&format!("{} = {}", name.to_lowercase(), val), writer);
            }
            TreeKind::Function { name, decls, statements, .. } => {
                self.output(&format!("def {}(self):", name.to_lowercase()), writer);
                self.ident += 1;
                for d in decls {
                    self.generate(d, writer)?;
                }
                if statements.is_empty() {
                    self.output("pass", writer);
                } else {
                    for s in statements {
                        self.generate(s, writer)?;
                    }
                }
                self.ident -= 1;
                self.output("", writer);
            }
            TreeKind::FuncCall { name, ret_val } => {
                if let Some(rv) = ret_val {
                    self.output(&format!("{} = self.{}()", rv, name.to_lowercase()), writer);
                } else {
                    self.output(&format!("self.{}()", name.to_lowercase()), writer);
                }
            }
            TreeKind::While { condition, op, statement } => {
                let cond_str = self.format_condition(condition, *op);
                self.output(&format!("while {}:", cond_str), writer);
                self.ident += 1;
                self.generate(statement, writer)?;
                self.ident -= 1;
            }
            TreeKind::If { condition, op, then_body, else_body } => {
                let cond_str = self.format_condition(condition, *op);
                self.output(&format!("if {}:", cond_str), writer);
                self.ident += 1;
                self.generate(then_body, writer)?;
                self.ident -= 1;
                if let Some(eb) = else_body {
                    self.output("else:", writer);
                    self.ident += 1;
                    self.generate(eb, writer)?;
                    self.ident -= 1;
                }
            }
            TreeKind::Switch { cases } => {
                self.output("match self.token.token_type:", writer);
                self.ident += 1;
                for case in cases {
                    let mut labels = Vec::new();
                    for label in &case.labels {
                        if let TreeKind::TermName(name) = &label.kind {
                            labels.push(format!("TokenType.{}", name));
                        } else if let TreeKind::ExpName(name) = &label.kind {
                            labels.push(format!("TokenType.{}", name));
                        }
                    }
                    if labels.is_empty() { continue; }
                    self.output(&format!("case {}:", labels.join(" | ")), writer);
                    self.ident += 1;
                    self.generate(case.statement, writer)?;
                    self.ident -= 1;
                }
                self.output("case _:", writer);
                self.ident += 1;
                self.output("pass", writer);
                self.ident -= 1;
                self.ident -= 1;
            }
            TreeKind::Statements(list) => {
                if list.is_empty() {
                    self.output("pass", writer);
                } else {
                    for s in list {
                        self.generate(s, writer)?;
                    }
                }
            }
            TreeKind::Return(val) => {
                if let Some(v) = val {
                    self.output(&format!("return {}", self.map_init(v)), writer);
                } else {
                    self.output("return", writer);
                }
            }
            TreeKind::Literal(s) => {
                if s.starts_with("//") {
                    self.output(&format!("# {}", &s[2..]), writer);
                } else {
                    self.output(&self.map_init(s), writer);
                }
            }
            TreeKind::TokenGet(_name) => self.output("self.token = self.tokenizer.get_token()", writer),
            TreeKind::EmbedCode(code) => {
                let processed = code.replace("$$", "ret_val").replace("$", "ret_val_");
                for line in processed.split(';') {
                    let trimmed = line.trim();
                    if !trimmed.is_empty() {
                        self.output(trimmed, writer);
                    }
                }
            }
            _ => {}
        }
        Ok(())
    }
}
